### ISSUE TITLE
Absolute path is treated as a relative path

### ISSUE THREAD

**Issue by onurcanbektas** [quarto-dev/quarto-r#10]
I'm trying to include a figure into a .qmd file file as

`![](`r here::here("data/F220416/F220416S2214/raw/IMG_1785.png")`)`
(`here` library makes sures that the path is an absolute path)

But in the html file that is created, the resulting path looks like

`<p><img src="./Users/onurcanbektas/junction/projects/apm.alim.raedler/data/F220416/F220416S2214/raw/IMG_1785.png" class="img-fluid"></p>`

i.e the absolute path has `.` in front of it. 

During the rendering, quarto is warning me that I supplied an absolute path, so it is recognising that it is absolute, but still treats it as a relative path. I think this behaviour is unintendend, hence a bug.

**Comment by cderv** [comment]
Hi, 

I don't think this is an issue with quarto directly. By using inline R code with the **here** package, you are explicitly asking for an absolute path. This is included in the HTML file, and will be treated as a HTML file path. You can find more about relative path and absolute path in HTML in https://bookdown.org/yihui/blogdown/html.html#html
IMO quarto can't really decide if the absolute path provided should be transformed to relative or not, as sometime you may want to use absolute path in a HTML document. 

When you want to include an image using R code, I would suggest to use `knitr::include_graphics()`. It will also warn on absolute path and there was a recent discussion about that. See https://github.com/yihui/knitr/issues/2119
Also, with `knitr::include_graphics()`, you could use `xfun::from_root()` instead of `here::here()` to create a relative path from the root of the project. 

Anyway, if you think this is really something to improve within Quarto, you can open a discussion in  the CLI repo: https://github.com/quarto-dev/quarto-cli/discussions

This repo `quarto-r` is about the R package itself which is only a wrapper around the CLI for easier calling in R. 

Thanks!
