### ISSUE TITLE
Relative links for images outside of presentation folder successfully preview, but break on render

### ISSUE THREAD

**Issue by DallasNovakowski** [quarto-dev/quarto-r#131]
Not sure whether this belongs in quarto-cli

There seems to be an intentional shift in Quarto to use relative instead of absolute paths. In particular, these paths are relative to the .qmd file. 

This may have produced a behaviour where images are not rendering properly if they lie outside of the same folder as the .qmd file. The images will correctly display as part of the automatic 'preview' in the source pane, but when the document is rendered, it returns the broken image icon in its place.

This is even the case if we were to use `here::here` or `xfun::from_root`. Using these functions work for sourcing external r scripts that follow the same directory structure, so seems to be something special with images. Using the [`execute-dir: project` option](https://quarto.org/docs/projects/code-execution.html#working-dir) does not seem to resolve the issue.

This issue has been brought up in the community postings [by John Graves](https://community.rstudio.com/t/images-preview-but-are-broken-in-quarto-presentation/141082/4), and [Andy Field](https://community.rstudio.com/t/quarto-presentation-using-relative-links-outside-of-presentation-folder/136838).

**I have copied and modified a Posit Cloud project from Jon Graves' post demonstrating the behaviour: <https://posit.cloud/content/6847700>**. There are three qmd files: one that works (at the project root), and two that don't work (in the presentations folder).

This may be relevant to [discussions in the renderthis package](https://github.com/jhelvy/renderthis/pull/73), although their concern seems to be placing rendered output in a separate directory, not sourcing files. 

There also seems to be [some discussion about making changes to how Quarto uses absolute vs. relative paths](https://github.com/quarto-dev/quarto-cli/issues/2440#issuecomment-1454141113). The practice of specifying directories has also been discussed in quarto-r issue #81, where @cderv [mentions the potentially evolving nature of how quarto handles outputs, inputs, and resources](https://github.com/quarto-dev/quarto-r/issues/81#issuecomment-1375691267).

Resolving this issue will help those of us that might want to use a pool of shared images across many different reports, whether across different lectures, or different report formats (e.g., posters, manuscripts, presentations). Addressing this may also resolve [quarto-r issue #94 posted by aputron](https://github.com/quarto-dev/quarto-r/issues/94).

**Comment by cderv** [comment]
> There seems to be an intentional shift in Quarto to use relative instead of absolute paths. In particular, these paths are relative to the .qmd file.

I don't know if there is a shift as I think this has always be the case. When rendering a single document, the linked used in Markdown image for example will be relative to the rendered directory. 

If you use tools to get it from a 'project' root (like `xfun::from_root()` or `here::here()`), this will correctly include a link to the `images/` folder you gave in your root. Hovewer, the image will only be shown in HTML preview locally (or online in RStudio Cloud) if the server that serve the files is correctly started from root of your project too. And by default this is not the case: When you render a single document! 

Try running `server::http('.')` from your RStudio project root, and navigate to the presentations in sub folder - images will show because now `images/` folder is correctly accessible from the web server. 

Without this, only the  web server was started at the subfolder level for the HTML in the subfolder, and `../images` does not exist in that case. 

I hope this is clear. 

> Resolving this issue will help those of us that might want to use a pool of shared images across many different reports, whether across different lectures, or different report formats (e.g., posters, manuscripts, presentations).

When adopting this strategy, you need to really about projects for sources and outputs you produce. 

First of all, you should really consider using Quarto projects if you want to manage your .qmd as a project. Currently in your RStudio cloud example, this is only a RStudio project, which is not the same. 

When using Project, Quarto will know a `.qmd` file rendered is part of a project. And in that case, there are some nice options like path resolution from project, and preview from project root. 

So if you add a `_quarto.yml` file with this content
````yaml
project: 
  type: default
````

Now you can render the document in subfolder, and you should see image. 

You should also be able to path like this starting with a `/`
````markdown
![](/images/llama.png)
````

which means "relative to project root". Which avoid doing `..` many times in some cases. 

> Using the [execute-dir: project option](https://quarto.org/docs/projects/code-execution.html#working-dir) does not seem to resolve the issue.

This should not be useful for image path IMO. This options for **knitr** is quite advanced, and allow to change the working directory from which **knitr** chunk are evaluated. If this is only a filepaths problem, using `here::here()` or `xfun::from_root()` should work ok. 

> This may be relevant to https://github.com/jhelvy/renderthis/pull/73, although their concern seems to be placing rendered output in a separate directory, not sourcing files.

Yes this and other `quarto-r` issue is about `output-file`. Quarto will not allow to output in another directory not relative to the .qmd. If this is expected, it should be a two step process using wrapper function or scripts: Render the document then move the outputs. 

Quarto projects of type Website or Manuscript will do some copying of results into a `output-dir` and it includes resources so that when deploying the output-dir, everything is at the right relative place from the HTML files. 

So overall, try to use Quarto Projects, and then see if there is still some undesired behaviors. 

Hope it helps.

**Comment by DallasNovakowski** [comment]
Amazing! Thank you.

I've left the original project as-is, but for any future readers, I've created an updated project that incorporates the fix <https://posit.cloud/content/6927922>, so you can see the change.

For novices like me:

Option 1: You can do the fix just as Cristophe says, create a new Quarto Project, and in the automatically-generated `_quarto.yml` file, put:

```
project:
  title: "my_project_name"
  type: default
```

Option 2: You can implement the fix without needing to start a Quarto Project from scratch. In your a RStudio Project, you can just click "new blank file" --> "text file", and name it `_quarto.yml` (which will automatically convert the icon), and place it at the project root. Put in the same `project:` information as option 1.

**Comment by giabaio** [comment]
I think I have an issue related to this (although it's perhaps a bit bigger than that...). I am using revealjs slides and I have R chunks that compile some figures, something like
```
#| echo: false
#| eval: true
#| out-width: "80%"
#| label: binom-sampling
theta=.25
n=20
tibble(
  x=seq(0,20),
  y=dbinom(seq(0,20),n,theta)
) |> ggplot(aes(x=x,y=y)) + geom_bar(stat="identity") + 
  xlab("$y$") + ylab("Distribution function") + 
  labs(title="Sampling distribution given $\\theta=0.25,n=20$")
```
Now: if I use `dev: tikz` (which makes for nicer resulting images, as they are processed by LaTeX), the resulting image is stored in the root of my R project. If I don't, then the image is stored under /xxx_files/figure-revealjs/...

It's not necessarily a *huge* deal, but it makes for a very messy folder, which I would then want to publish to show my slides... And of course, the resulting html file would point to the image /image1.png so I can't move them post-hoc... 

Am I missing something obvious? I think I have used exactly this sort of construction in the past and I never had this problem before (= all the images would be stored under /xxx_files/figure-revealjs/...). Now it's stopped doing this. I've just updated quarto from the GitHub repo, just in case, but to no resolution (so that should not be the issue). 

Here's a replicable example (hopefully!):

---
title: "My slides"
format: revealjs
author: GB
html: 
  fig-format: png
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
```

## Aside: Likelihood function

:::: {.columns}

::: {.column width="50%"}
#### Sampling distribution

```{r}
#| echo: false
#| eval: true
#| out-width: "80%"
#| label: binom-sampling
theta=.25
n=20
tibble(
  x=seq(0,20),
  y=dbinom(seq(0,20),n,theta)
) |> ggplot(aes(x=x,y=y)) + geom_bar(stat="identity") + 
  xlab("$y$") + ylab("Distribution function") + 
  labs(title="Sampling distribution given $\\theta=0.25,n=20$")
```
:::

::: {.column width="50%"}
#### Likelihood function

::: {.absolute top=370}
```{r}
#| echo: false
#| eval: true
#| out-width: "80%"
#| dev: "tikz"
#| label: binom-likelihood
n=20
y=4
lik=function(theta,y,n) {
  theta^y*(1-theta)^(n-y)
}
tibble(
  theta=seq(0,1,.01),
  l=lik(seq(0,1,.01),y,n)
) |> ggplot(aes(theta,l)) + geom_line() + xlab("$\\theta$") + 
  ylab("Likelihood") + 
  labs(title="Likelihood function given $y=4,n=20$")
```
:::
:::

::::

NOTE that I have a setup.R file automatically loaded that gives this instruction
```
# Trick to automatically convert pdf graphs generated with dev='tikz' into png so they work in html format
# see: https://github.com/rstudio/bookdown/issues/275
knitr::opts_hooks$set(dev = function(options) {
  if (identical(options$dev, 'tikz') && !knitr:::is_latex_output()) {
    options$fig.process = function(x) {
      if (!grepl('[.]pdf$', x)) return(x) 
      x2 = sub('pdf$', 'png', x)
      magick::image_write(magick::image_read(x,density=300), x2, format='png',quality=100)
      x2
    }
  }
  options
})
```
(but I don't think that's relevant to my issue above...).

Any help, please?
