### ISSUE TITLE
`quarto_render()`: invisibly return paths of all rendered files on success

### ISSUE THREAD

**Issue by alexpghayes** [quarto-dev/quarto-r#14]
This would make it much nicer to use `quarto_render()` with @wlandau's `targets` package to produce large volumes of parameterized reports. Currently it's a bit painful to produce parameterized reports when there are multiple output formats and you would like to render to them all at once in a targets pipeline.

If there some other easy way to programmatically access the names/paths of rendered files, that would also be great.

**Comment by wlandau** [comment]
In fact, it would be really nice if `quarto_inspect()` could accept an `output_format` argument (which could be a vector) so Quarto could tell `tarchetypes` exactly which files it will generate (files which `targets` should track for changes). Came up in https://github.com/ropensci/tarchetypes/discussions/102.

**Comment by wlandau** [comment]
Another edge case came up at https://github.com/ropensci/tarchetypes/discussions/107. If there is a simple `_quarto.yml` file, then `quarto_inspect("single_report.qmd")` does not show the output directory where `quarto_render("single_report.qmd")` will store `single_report.html`. For integration with `targets`, it would be extremely helpful if `quarto_inspect()` could straightforwardly list all the output files, with directory paths included, that will be generated by `quarto_render()`. Otherwise, `tarchetypes` would need to emulate the output file policies of Quarto, which could change if Quarto changes.

**Comment by cderv** [comment]
Thanks for your feedback. I wonder if this kind of feature shouldn't be more generic that just the R package. I believe this discussion could be related https://github.com/quarto-dev/quarto-cli/discussions/2372 
You may want to contribute to the discussion there. 

Probably `quarto inspect` or a variant should try to handle that. If it is not in the scope of the CLI, we can see what could be done at the R level after running `quarto`.

**Comment by wlandau** [comment]
Sure, sounds good. I opened https://github.com/quarto-dev/quarto-cli/discussions/2378 and referenced this thread.

**Comment by cderv** [comment]
I opened an issue directly to track this more clearly in `quarto-cli` - this needs to be done there IMO
* https://github.com/quarto-dev/quarto-cli/issues/8397

**Comment by wlandau** [comment]
Thank you, this would really help!
