### ISSUE TITLE
How to setup the R path for Quarto for VS Code?

### ISSUE THREAD

**Issue by lux5** [quarto-dev/quarto-r#31]
`ERROR: Error executing 'Rscript': program not found

Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/`

Could anyone tell me how to set up a customised path for R? I got R installed in the local drive (not in a system default folder as I don't have the Admin privilege). I couldn't find any place where I could reset my R path.

**Comment by arnold-c** [comment]
I suspect this would be better served on the [VSCode-R repo](https://github.com/REditorSupport/vscode-R), but to help it would be useful to have more information about your setup. What's your OS, and do you use [radian](https://github.com/randy3k/radian)?

Assuming you're on a Unix-based system, what do you get when you type `which R (or radian)` into the terminal? You can put the output in the appropriate "Rterm: Linux/Mac" section of the VSCode R settings (for me it's `/Users/user/.pyenv/shims/radian`)

**Comment by lux5** [comment]
> I suspect this would be better served on the [VSCode-R repo](https://github.com/REditorSupport/vscode-R), but to help it would be useful to have more information about your setup. What's your OS, and do you use [radian](https://github.com/randy3k/radian)?
> 
> Assuming you're on a Unix-based system, what do you get when you type `which R` (or `which radian`) into the terminal? You can put the output in the appropriate "Rterm: Linux/Mac" section of the VSCode R settings (for me it's `/Users/user/.pyenv/shims/radian`).
> 
> Also, are you trying to render a Quarto document through the terminal, or through your R console? I've had issues with the Quarto CLI not accessing all my packages when in `{renv}` projects, but running it in the R console doesn't cause issues.

Sorry for not providing the extra information.
I am using Windows 10 with the latest radian installed for one of my conda envs, and I have also installed the latest [VSCode-R](https://github.com/REditorSupport/vscode-R), the R console is working well. However, when rendering my qmd files, it just couldn't locate the location where my R folder is (I actually installed R under my customised location). In the setup panel of this extension, I cannot find the places where I could setup my R's location. Could you give me a hand? Many thanks.

**Comment by arnold-c** [comment]
OK. It's been a while since I've used R in windows, but I'm assuming have your R executable (and radian) in your PATH? Can you open up an R session from the command line (i.e. not opening the R GUI console)? If so, can you try opening an R session in the workspace directory and then running `r$> quarto::quarto_render("file.qmd")` to check if it's an issue with the R installation or VSCode setup?

If you type in "Rterm" into VSCode's settings search bar you should see and option for windows.

<img width="486" alt="Screen Shot 2022-07-31 at 22 06 16" src="https://user-images.githubusercontent.com/24391445/182058679-73336679-0986-4e85-85e5-147fad4c4673.png">

On another note, you may also need to set up a custom `.libPaths()` given you have R in a non-default location. You should be able to specify this in VSCode by searching for "libPaths" in the settings again.


<img width="522" alt="Screen Shot 2022-07-31 at 22 18 27" src="https://user-images.githubusercontent.com/24391445/182059725-4b1a6799-1a8d-44c1-afb6-9eaa8daff11d.png">

**Comment by lux5** [comment]
[](url)> OK. It's been a while since I've used R in windows, but I'm assuming have your R executable (and radian) in your PATH? Can you open up an R session from the command line (i.e. not opening the R GUI console)? If so, can you try opening an R session in the workspace directory and then running `r$> quarto::quarto_render("file.qmd")` to check if it's an issue with the R installation or VSCode setup?
> 
> If you type in "Rterm" into VSCode's settings search bar you should see and option for windows.
> 
> <img alt="Screen Shot 2022-07-31 at 22 06 16" width="486" src="https://user-images.githubusercontent.com/24391445/182058679-73336679-0986-4e85-85e5-147fad4c4673.png">
> 
> On another note, you may also need to set up a custom `.libPaths()` given you have R in a non-default location. You should be able to specify this in VSCode by searching for "libPaths" in the settings again.
> 
> <img alt="Screen Shot 2022-07-31 at 22 18 27" width="522" src="https://user-images.githubusercontent.com/24391445/182059725-4b1a6799-1a8d-44c1-afb6-9eaa8daff11d.png">

Many thanks and so sorry for the late reply.

I can use R (radian) in VSCode with no problem. But just cannot render the qmd file that I could in RStudio. I have tried the following:

![Capture](https://user-images.githubusercontent.com/11221075/183312292-e17af2b6-6cbd-4c3d-ae94-dc127ee99f15.PNG)

I also tried adding the extra path where my `Rscript.exe` is located to `R's .libpaths()` as you recommended.

![Capture2](https://user-images.githubusercontent.com/11221075/183312429-0a745f00-ccbf-4082-b2f7-50131d591fcd.PNG)

The same error. I think that it would be better if more options for the Quarto extension are given to customise the R path.

**Comment by arnold-c** [comment]
Not a problem about the delay.

I'm afraid that I'm not sure how much more help I can be, but as a final check, what happens when you set the Quarto CLI Path?

<img width="693" alt="Screen Shot 2022-08-08 at 13 21 08" src="https://user-images.githubusercontent.com/24391445/183476391-55bf18b1-ccd8-41bd-a5ed-c07a9b475f33.png">

**Comment by lux5** [comment]
> Not a problem about the delay.
> 
> I'm afraid that I'm not sure how much more help I can be, but as a final check, what happens when you set the Quarto CLI Path?
> 
> <img alt="Screen Shot 2022-08-08 at 13 21 08" width="693" src="https://user-images.githubusercontent.com/24391445/183476391-55bf18b1-ccd8-41bd-a5ed-c07a9b475f33.png">

I didn't set up any path for this one, because the extension asked me to install CLI when I click the render button for the first time. After I install Quarto CLI - no further popping up of the install request window, and it seems Quarto CLI has been successfully installed.

**Comment by cderv** [comment]
Sorry for the delay on this. This is the issue thread of the R Package quarto, and we are not thoroughly following as we do for the main project at [quarto-dev/quarto-cli](https://github.com/quarto-dev/quarto-cli/)

Is this still an issue ? It seemed it was something with VS CODE in the first place. 

If this is still an issue, please do open anything related to vscode in https://github.com/quarto-dev/quarto
