### ISSUE TITLE
Hand over variables between files is not working

### ISSUE THREAD

**Issue by joundso** [quarto-dev/quarto-r#36]
# Problem
So far we use RMarkdown to create analyses and related publications. For this purpose we have created several `.rmd` documents, which are included one after the other in a bundling `.rmd` file and together create the final document. Different variables are created in different places of the included files and sometimes used and included in multiple places (in different `.rmd` files).
For example, the "data-wrangling" and "preprocessing" is done with little Markdown output in the first `.rmd` files, and the text-heavy subsequent parts refer to the previously prepared data in several places and includes it dynamically in different places.
With the big announcement of Quarto and all the advantages that come with it, we would like to map the same in Quarto, but it seems that the transfer of variables from one to another `.qmd` document is not possible, even if these documents are not rendered individually and separately but bundled together e.g. in a book.

Maybe this is related to #29.

# Expected behavior
I would expect that that if a variable is assigned in one "chapter" of the book, it can be used in another chapter that follows it, without having to re-source everything in each chapter manually. This would be a huge drawback.

# Demo code

## quarto

Minimal quarto code example: https://github.com/joundso/quarto-book-test/tree/master/qmd-project
The book is defined [here](https://github.com/joundso/quarto-book-test/blob/master/qmd-project/_quarto.yml) and sources [`intro.qmd`](https://github.com/joundso/quarto-book-test/blob/master/qmd-project/qmd/intro.qmd) (here the variable `object_from_intro` is created) and [`summary.qmd`](https://github.com/joundso/quarto-book-test/blob/master/qmd-project/qmd/summary.qmd) (where the variable `object_from_intro` is dynamically used).

The creation of this book fails because the variable `object_from_intro` is not available when rendering `summary.qmd`, although it was created in the previously rendered `intro.qmd`.

### Error message of the quarto project
Error:
```bash

Rendering:
[1/3] index.qmd
[2/3] qmd/intro.qmd


processing file: intro.qmd
  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: unnamed-chunk-1
  |......................................................................| 100%
  ordinary text without R code


output file: intro.knit.md

[3/3] qmd/summary.qmd


processing file: summary.qmd
  |......................................................................| 100%
   inline R code fragments

Quitting from lines 2-3 (summary.qmd) 
Error in eval(parse_only(code), envir = envir) : 
  object 'object_from_intro' not found
Calls: .main ... inline_exec -> hook_eval -> withVisible -> eval -> eval

Execution halted
```

## RMarkdown

The same with RMarkdown works perfectly:
- [Rmd Code](https://github.com/joundso/quarto-book-test/tree/master/Rmd-project)
- [Rmd Result](https://htmlpreview.github.io/?https://github.com/joundso/quarto-book-test/blob/master/Rmd-project/docs/_main.html)

**Comment by joundso** [comment]
As an interim solution I currently use the following:

**`_quarto.yml`** looks like the following (note that it only inclues the `index.qmd` and no other chapters:

```yml
project:
  type: book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "8/18/2021"
  chapters:
    - index.qmd


format:
  html:
    theme: cosmo
```

And the **`index.qmd`** includes all the files:

```qmd
# Heading

{{< include qmd/intro.qmd >}}
{{< include qmd/summary.qmd >}}
```

Disadvantage: Only the heading 'Heading' is shown in the main table of contents (but there is a second table of contents which lists all included headings correctly)

**Comment by cderv** [comment]
Hi @joundso, 

Sorry for the delay on this - this is the issue board of the R package quarto and we don't look at it as thoroughly as the Quarto CLI which is the main project. https://github.com/quarto-dev/quarto-cli

I'll try to answer anyway your comment with current status, but your question could be updated and asked again in our Discussion  Board https://github.com/quarto-dev/quarto-cli/discussions

> I would expect that that if a variable is assigned in one "chapter" of the book, it can be used in another chapter that follows it, without having to re-source everything in each chapter manually. This would be a huge drawback.

Unfortunately, it does not work yet that way. Quarto works differently than bookdown and each document is rendered on its own. For passing value between several rendering, it needs to be implemented at the execution level using cached value for example or external storage for saving and loading. This is a limitation due to Quarto being language agnostic and compatible with many languages: Each render happens on its own R Session. 

However, we are aware of the need and this may evolve in the futures. See https://github.com/quarto-dev/quarto-cli/discussions/431 and others their. 

Project script features may help to organize rendering with saved files and data. https://quarto.org/docs/projects/scripts.html

Saving objects to files (or caching) is possible in many ways with R as a lot of packages offers options for that. One "easy" or just straightforward way would be to save a .Rdata file that would be loaded by each R session during the different rendering. This way the whole R session would be saved. More targeted savings of the data you need could be safer though. 

I hope it helps understand current situation. 

I let you open a discussion on Quarto repo for more exchange with the rest of the Quarto team. 

Thank you !
