### ISSUE TITLE
How to set working directory from Quarto YAML during interactive execution?

### ISSUE THREAD

**Issue by Dijkie85** [quarto-dev/quarto-r#56]
Is there a way to reproduce the functionality of `knitr::opts_knit$set(root.dir = '/path/to/dir')` from Rmarkdown (which does work in Quarto as well, when ran from a chunk) but straight from the YAML block? Something like:

```
---
knitr:
  options:
    root:
      dir: "/path/to/dir"
---
```

(I've tried it, and also substituting `options` with `opts_knit`, and it doesn't work.

Thank you!

**Comment by cderv** [comment]
`working_dir` is the setting in Quarto: https://quarto.org/docs/projects/code-execution.html#working-dir

I don't know if this is supported interactively in RStudio IDE or in VSCODE. 

Please do confirm is this is working or not. In any case, this would be an issue for RStudio IDE as Quarto support, or VS CODE extension for Quarto

**Comment by Dijkie85** [comment]
Thank you @cderv for your reply. Unfortunately that didn't work either. The setting refered to in the link you provided (`project: execute-dir: project`) works ok for rendering, but still won't do for interactively running chunks in a Quarto notebook. I'll post in the Rstudio IDE repo. Thanks!

**Comment by cderv** [comment]
> but still won't do for interactively running chunks in a Quarto notebook.

For Interactive use, this is indeed a topic for the IDE. You should open an issue there so that it knows to respect some options. 

It seems like this feature is type to project configuration. Quarto heavily rely on project structure.

I'll close this here. Please do open a new issue for this specific file interactive behavior in rstudio ide repo
