### ISSUE TITLE
There is no possibility to transfer environment to the quarto_render

### ISSUE THREAD

**Issue by avraam-inside** [quarto-dev/quarto-r#63]
There was an `envir` argument in `rmarkdown::render`, but now it is missing in `quarto::quarto_render`.

A very important argument, please add.

**Comment by cderv** [comment]
Have you look closer to how Quarto is working and the difference with R Markdown ? 
Do you understand that Quarto is not an R Package only like R Markdown but a CLI tool that will know how to run R but also Python and other language ? 

>  but now it is missing in quarto::quarto_render.

`quarto_render()` is not a replacement of `render()` in R Markdown. It is just a wrapper in R to call `quarto render` in your terminal for you from R. It works completely differently because Quarto is not coded in R. 

This means that when you are calling `quarto render` you are not in a R environment - so there is no `envir` argument to pass. 

You need to do things differently in your project if you were relying on the `envir` argument of `rmarkdown::render()` - Quarto when rendering will only execute R for the evaluation of the cells in an independant background R session. It will be opened and closed during the rendering of a document. 

Hope it helps understand.

**Comment by cderv** [comment]
Duplicate of #29
