### ISSUE TITLE
Is there life here?

### ISSUE THREAD

**Issue by avraam-inside** [quarto-dev/quarto-r#77]
Is there life here?

For more than a month, 3 requests for critical improvements have been hanging: 
https://github.com/quarto-dev/quarto-r/issues/62
https://github.com/quarto-dev/quarto-r/issues/63
https://github.com/quarto-dev/quarto-r/issues/64

But these problems are not something that has not yet been solved, there is no reaction.

Tell me please:
1) Why does this section of github exist if there has been no reaction to requests here for weeks or months? Maybe this section should be closed?
2) Where should I write so that all the same requests for improvements receive a reaction and get to work?

Despite the fact that there are still a lot of smaller problems in the quart, for which I would like bugfixes, but even for such critical ones there is no reaction at all.

The request is either to say where to write requests so that there is a reaction, or take the above problems into work, please.

**Comment by cderv** [comment]
Sorry for the delay - you are asking your questions in a side project which the R package Quarto and not the main project. 
The Quarto website have links toward where to open issues and where to asked questions 
![image](https://user-images.githubusercontent.com/6791940/211335091-10985c72-33ec-4983-85a1-1a3972af9494.png)

This is best to ask in the right place to have quicker answer - we don't work on the R wrapper package as often as the main Quarto CLI tool which is our main focus. 

> Why does this section of github exist if there has been no reaction to requests here for weeks or months? Maybe this section should be closed?

This is for the R package Quarto which is on CRAN - we don't work on the package at the same path that the CLI because it brings no specific feature as it is a wrapper of the R package. We follow daily the issues in Quarto issue tracker and discussion forum. 

This issue board is still here for specific R package Quarto issue. 

> Where should I write so that all the same requests for improvements receive a reaction and get to work?

Ask in the right place following the links provide in our main documentation website 

> Despite the fact that there are still a lot of smaller problems in the quart, for which I would like bugfixes, but even for such critical ones there is no reaction at all.

I have now answer to your different issues opened. Some of the issues where just question to answer and not real issue to solves. Please do open discussion in Quarto Discussion board to share your feedback after having read the documentation properly to understand the tooling and the vision. We'll do our best to take the improvement idea in the backlog. If you have issues, please do open a issue in the Quarto CLI repo with some reproducible example for use to look into. 

Hope it helps understand better how this is organized.
