### ISSUE TITLE
Is there any scope for rendering the .qmd file in server and show the output in ui section of a shiny application?

### ISSUE THREAD

**Issue by rohit-el** [quarto-dev/quarto-r#82]
#### Example

I can render plotly objects in Shiny using ```plotly::renderPlotly()``` function in `server.R` file and use ```plotly::plotlyOutput()``` function in `ui.R` to show its output respectively. 

#### Requirements
I want to allow a user to type `.qmd` content in a editor in my Shiny application and preview it in same page (or may be another Tab).

**Is it something that can be done using this `quarto` package in R?**

**Comment by cderv** [comment]
Hi! 

I may not be understanding your example correctly and more globally your use case. 

**quarto** R package is a wrapper around the CLI `quarto`  (https://quarto.org/) so that a user can call Quarto from R code instead of terminal or IDE only. That is all mostly. You can find all the functions available in the package's doc https://quarto-dev.github.io/quarto-r/

> I want to allow a user to type .qmd content in a editor in my Shiny application and preview it in same page (or may be another Tab).

You would need to code that yourself in your application i.e probably find a tool to have a editor in your shinyapp, then save the content to a file, render it within quarto on the server, deal with output and build the UI from the rendered doc using some shiny functions. 

I don't think **quarto** can do much more regarding helping with shiny. 

Please do add more information and explanation if I misunderstood. THanks

**Comment by rohit-el** [comment]
That is what I assumed @cderv. Thank you for your detailed explanation.
