### ISSUE TITLE
Setting Images Directory

### ISSUE THREAD

**Issue by aputron** [quarto-dev/quarto-r#94]
Hey!

I just recently started using Quarto, and was wondering if there was a way to set an images directory?

I understand you can copy images into a quarto file, and it makes a folder with your image in the current directory.

Can we set a specified `images` path?

**Comment by cderv** [comment]
Hi, thanks for reaching out. Sorry for getting to you on this so late. You will have quicker answer next time if you ask directly in main project repo for Quarto related questions (https://github.com/quarto-dev/quarto-cli/discussions)

Since then did you manage to use Quarto as you wished ? I'll try to give some answers but please to ask in your need further help. 

For Quarto, you can't use absolute paths outside of a project, but you can have a project-wide folder without your resource. We mention this in site resources (https://quarto.org/docs/websites/website-tools.html#site-resources) 

> Images are the most commonly used type of resource file. If you have global images (e.g. a logo) that you want to reference from various pages within your site, you can use a site-absolute path to refer to the images, and it will be automatically converted to a relative path during publishing. For example:
> ````markdown
> ![](/images/logo.png)
> ````


Hope it helps
