### ISSUE TITLE
Displaying callouts on index.qmd in book

### ISSUE THREAD

**Issue by ShanSabri** [quarto-dev/quarto-r#97]
I am working on a Quarto Book using R and have several callouts through my chapters. Is it possible to have all these callouts displayed over to a single qmd file, presumably the `index.qmd`?

The goal is to have a single chapter of the book capture all the callouts.

**Comment by cderv** [comment]
Hello. 

Sorry for getting back to you so late on this. This is definitely not a R package question. You'll get quicker answer if you ask your question on main repo in discussion: https://github.com/quarto-dev/quarto-cli/discussions/

> Is it possible to have all these callouts displayed over to a single qmd file, presumably the index.qmd?

There is no feature for this built-in. 

With Quarto, this could probably be done using filters (https://quarto.org/docs/extensions/filters.html) with Lua (https://quarto.org/docs/extensions/lua.html)

Custom ast node like `Callout` can be targeted since 1.3 (https://quarto.org/docs/prerelease/1.3/ast.html) and so you retrieve them all and do something with them. 

That would be one way. You could probably parse the file in R and retrieve the block. 

Anyhow, this is not specific to R package quarto, so I'll close this.
